### ISSUE TITLE
Clicking "back" browser arrow and going back into room adds duplicates of user to UserList

### ISSUE THREAD

**Issue by MichaelVoth** [jejcode/madlibs#43]

**Comment by jejcode** [comment]
This doesn't happen for me. I'm not sure if something I did in the last pull fixed it? I incorporated a sessionStorage item to add and delete the room id. Regardless, I'm not able to duplicate the error.

**Comment by MichaelVoth** [comment]
This happens when you enter a room, press back, and the click join room again. It sends a USER_JOINED_ROOM twice.
